### ISSUE TITLE
Clicking an empty part of the map opens an empty popup

### ISSUE THREAD

**Issue by dabreegster** [cyipt/actdev-ui#1]
![screencast](https://user-images.githubusercontent.com/1664407/106314879-3bb29680-621f-11eb-82b4-1d4ae796949d.gif)
Happens with any combination of layers enabled, not just collisions

**Comment by mvl22** [comment]
Yes, there are lots of known bugs like this.

I would recommend not logging bugs during this coming week, as it's only an early alpha which we've not had time to bugfix yet.
