### ISSUE TITLE
abstreet data files aren't being served

### ISSUE THREAD

**Issue by dabreegster** [cyipt/actdev-ui#10]
@mvl22, Is there some issue with the cronjob that deploys things? https://github.com/cyipt/actdev/releases/tag/0.1.9 should be the latest.

I would expect `wget https://actdev.cyipt.bike/abstreet/data/system/gb/poundbury/maps/center.bin.gz` to hand back a 3.1MB file with md5sum 3a68ef5650e05eab3ef934521ca734b6. I'm getting back the HTML page with the main UI instead. I've tried a few variations of this URL in case I messed up the directory structure, but I can't figure out what's going on.

@Robinlovelace, in the meantime, you can see all the actdev sites with scenarios from the S3 deployment: abstreet.s3-website.us-east-2.amazonaws.com/dev/game/?--actdev=poundbury

**Comment by Robinlovelace** [comment]
Great to see @dabreegster, looking at http://abstreet.s3-website.us-east-2.amazonaws.com/dev/game/?--actdev=allerton_bywater right now, looking good!

**Comment by mvl22** [comment]
Looks like it ran into a permissions issue; now resolved.

Git clone is so much easier :)
