### ISSUE TITLE
Pass --cam parameter to A/B Street

### ISSUE THREAD

**Issue by dabreegster** [cyipt/actdev-ui#14]
`/abstreet/?--actdev={properties.site_name}&--cam=16.55/51.021719/-3.097436`

I'm not familiar with JS generally or the framework in particular. Is there a way to make the `popupHtml` contents pull dynamically from the current view? A hacky way of getting the current params would be to scrape `window.location.href`, but I'm sure there's a proper API through mapbox-gl.

**Comment by mvl22** [comment]
Yes, I’ll sort this.

**Comment by dabreegster** [comment]
Thanks! Works in Chromium for me, but I'm not sure it's working in Firefox, though:
![Screenshot from 2021-02-17 12-05-30](https://user-images.githubusercontent.com/1664407/108261459-85084e80-7118-11eb-8fed-31cb088766e3.png)
Brings me to https://actdev.cyipt.bike/abstreet/?--actdev=kidbrooke-village&--cam=

But the firefox devconsole shows that this property exists:
![Screenshot from 2021-02-17 12-09-29](https://user-images.githubusercontent.com/1664407/108261856-0829a480-7119-11eb-824b-69a88abfe6c8.png)

Can anybody else repro, or is this just something with my browser?

**Comment by Robinlovelace** [comment]
I just tested on Windows + Firefox and it works: https://actdev.cyipt.bike/abstreet/?--actdev=kidbrooke-village&--cam=

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/108262304-ac810a80-715c-11eb-8a0f-f3fb9fd833d6.png)

**Comment by dabreegster** [comment]
An empty `--cam=` is the same problem I'm having. You should wind up with `--cam=15.02/51.46099/0.0305` or whatever was in the main site's URL

**Comment by Robinlovelace** [comment]
Ah yes I see what you mean...

**Comment by Robinlovelace** [comment]
Confirmed: not passing the camera url to the abstreet url.

**Comment by Robinlovelace** [comment]
Thinking out loud (or rather in typing) here are a couple of suggestions for slightly tightening the zoom level 2-3 connection:

- [ ] mention A/B Street more prominently in the app, e.g. in the `Study area` UI element (see image below)
- [ ] allow the user to set other things in A/B Street from the web UI, e.g. the time/scenario. Doable @dabreegster ?

![image](https://user-images.githubusercontent.com/1825120/108263407-25349680-715e-11eb-8726-e0e0bb4284a6.png)

Could that be switched to `Study Area / A/B Street launcher` or similar?

**Comment by dabreegster** [comment]
> allow the user to set other things in A/B Street from the web UI, e.g. the time/scenario

Doable, we can add flags for anything. Is it worth complicating this UI, though? The viewer doesn't have context on what different simulation time would mean yet before they see things moving around. And I'm probably going to make a very explicit "baseline / dutch" scenario button instead of
![Screenshot from 2021-02-16 18-01-35](https://user-images.githubusercontent.com/1664407/108263777-89823680-711b-11eb-8755-27d0c8484a0f.png) in abst itself

**Comment by Robinlovelace** [comment]
>  Is it worth complicating this UI, though?

Unsure. On reflection the 'base/dutch' option would probably be easier and more useful seeing as those concepts will already be in the app - heads-up @mvl22 and @Siequnu on integration/UX.

**Comment by Robinlovelace** [comment]
>  the 'base/dutch' option

Note we may rename the 'dutch' scenario. Any thoughts on that? I think 'base/active' or '2011/active' could be better names. Thoughts on that welcome? Discussed briefly with @joeytalbot but no decisions made.

**Comment by mvl22** [comment]
Can I suggest that discussion is held elsewhere, not on an issue about how to pass the map position to the --cam argument.

**Comment by mvl22** [comment]
OK, I think it's a timing bug. I can think of a theory why this might happen, though it shouldn't.

I'll rearchitect this - there's a more solid way of doing this, which I wasn't bothered to do for what is just an alpha UI, but we might as well get this to work to make testing easier over the coming week.

**Comment by mvl22** [comment]
Try now.

**Comment by dabreegster** [comment]
Working for me; thank you for the fix!

**Comment by Robinlovelace** [comment]
Confirmed. Screenshot below that could be useful for docs:

![image](https://user-images.githubusercontent.com/1825120/108275784-c1669980-716e-11eb-8dc3-1528d3d32947.png)


![image](https://user-images.githubusercontent.com/1825120/108275878-e2c78580-716e-11eb-963f-a4bbbc579739.png)

**Comment by Robinlovelace** [comment]
One more question on this, for @dabreegster, could the scenarios start at 07:00 by default? With the 08:30 morning peak and a normal distribution of departure times with a standard deviation of 20m, things should be kicking off a bit more by then making the A/B Street zoom level more immediately interesting and potentially immersive.

**Comment by dabreegster** [comment]
>  could the scenarios start at 07:00 by default

Sure, I'll make this change.

(Martin requested keeping issues on-topic; feel free to jump on one of the open issues like https://github.com/cyipt/actdev/issues/66 or start another)

**Comment by Robinlovelace** [comment]
> (Martin requested keeping issues on-topic; feel free to jump on one of the open issues like [cyipt/actdev#66](https://github.com/cyipt/actdev/issues/66) or start another)

Well @mvl22 complained to me about there being too many 'atomic' issues. Personally I prefer lots of small ones but raising sub-issues partly in response to that feedback ; )
