### ISSUE TITLE
Line hover occasionally does not clear

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/actdev-ui#17]
Just tried the Walking Routes in Handforth. On hover over, the routes go really wide. I also think there may be a bug that allows one route to stay selected/wide, as shown at the end of the gif. Know it's early days but worth getting everything out there early, especially bugs as I suspect this behaviour is.

Other point on walking routes that almost merits a new issue: because there is only one of them and we want to highlight walking, I wonder if we should put them above cycling and making them the first route/network/desire line layer we show. Thoughts? These kinds of things are part of the ongoing design process and don't want to put the cart before the horse but recent discussions suggest we need to make walking more prominent.

![Peek 2021-02-18 06-51](https://user-images.githubusercontent.com/1825120/108317534-5640b580-71b6-11eb-988f-9c8a95f6ba6d.gif)

**Comment by mvl22** [comment]
> I also think there may be a bug that allows one route to stay selected/wide, as shown at the end of the gif.

Just to say that, despite seeing that in the gif, I've so far (after 10 minutes of browsing and hovering) I've not managed to get a single reproduce of this.

I've also reviewed the code that handles this and can't see anything wrong:
https://github.com/cyclestreets/Mapboxgljs.LayerViewer/blob/master/src/layerviewer.js#L905-L929

(I've always felt that the way Mapbox GL JS have designed the hover handling is a bit poor - it's rather fussy. Leaflet.js does this much more elegantly.)

**Comment by mvl22** [comment]
> walking, I wonder if we should put them above cycling and making them the first route/network/desire line layer we show

Walking is now above cycling in the list:

![Screenshot 2021-03-05 at 19 01 44](https://user-images.githubusercontent.com/361423/110161434-40053d00-7de5-11eb-80f3-635457094f89.png)

but fastest route remains the default.

I can change this if you want, but it's a policy decision really for the PI, not me.

Personally I think that cycling remains a far more relevant aspect to facilitating mass travel. Walking is only going to be relevant to most people for very short trips. Experience in Cambridge is that people will cycle 5 miles if the infrastructure is good. Given that most people's work is not realistically within walking distance, my view remains that cycling is much more relevant to show.

**Comment by Robinlovelace** [comment]
To reproduce the app, go to a site (I can reproduce it with https://actdev.cyipt.bike/undefined/routes:type=/#11.09/53.3474/-2.1926 not tried others) and start clicking around on the walking routes. Trying to reproduce  with another GIF now...

**Comment by Robinlovelace** [comment]
![Peek 2021-03-06 07-28](https://user-images.githubusercontent.com/1825120/110198924-bdfd2e80-7e4d-11eb-8ba0-a119c43077e1.gif)

Managed to reproduce it. The GIF could be useful to help understand and perhaps debug other issues, notably #33 - note that the toggles seem to be broken in some sites now, a regression I think.

**Comment by mvl22** [comment]
OK, I've got a good reproduce case.

Ashton-park top-left consistently does this, and the others never do.

![Screenshot 2021-03-09 at 14 24 51](https://user-images.githubusercontent.com/361423/110485148-3fb9ba00-80e3-11eb-9788-b92151532963.png)

**Comment by mvl22** [comment]
I've spent half an hour so far looking at this, with no progress.

The code we're using is basically the boilerplate from the official Mapbox examples site. The logic looks correct to me; it just feels like a Mapbox GL JS bug frankly.

**Comment by Siequnu** [comment]
After leasing with Martin we narrowed this down to a bug in the Mapbox GL JS boilerplate code. Fixed in  [cyclestreets/Mapboxgljs.LayerViewer@81b5eed](https://github.com/cyclestreets/Mapboxgljs.LayerViewer/commit/81b5eedb644809e90a3c828017d0736ee4d68fc3)

**Comment by mvl22** [comment]
Pull request to upstream documentation example submitted at https://github.com/mapbox/mapbox-gl-js-docs/pull/524.
