### ISSUE TITLE
Change basemap

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/actdev-ui#2]
Looking at the map I think it's a bit busy and colourful, and will be even more so if we add colourful layers. Example from Leeds shown to illustrate the point.

How about a black and white default basemap? Thinking about colours building on https://github.com/cyipt/actdev/issues/48 - I think it's worth opening a project-wide colourscheme/vis identity issue at some point.

![image](https://user-images.githubusercontent.com/1825120/106661531-36e04080-6599-11eb-9bee-4b87929f19e6.png)

**Comment by mvl22** [comment]
The basemap issue is always a problem with a UI where lots of things are put on top.

The default tile layer is defined at:
https://github.com/cyipt/actdev-ui/blob/master/js/actdev.js#L26

and the available layer names are at:
https://github.com/cyclestreets/Mapboxgljs.LayerViewer/blob/master/src/layerviewer.js#L84-L161

The key issue is ensuring that the actual network (and ideally cycleways) are visible. Unfortunately that inherently makes the map busy.

If the Mapbox Streets design is too busy (I think its OKish), then take a look at the OS Outdoor layer (layer switcher in the bottom-left), which is very neutral and actually rather pleasant and modern. It would obviously mean showing Ordnance Survey data though.

We tried the night style, but while it looks cool, makes it very difficult to tell where anything actually is.

I think when the final UI user purposes are defined, and the design of the final UI then starts, this issue will naturally get mopped up within that work strand.

**Comment by Robinlovelace** [comment]
I think the MapBox Light style would be ideal as a base layer for colourful overlays: https://www.mapbox.com/maps/light

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/106663879-3dbc8280-659c-11eb-8f20-77730f9a3853.png)

**Comment by mvl22** [comment]
Yes that looks quite good - will add that in.

**Comment by Robinlovelace** [comment]
> Yes that looks quite good - will add that in.

Can it be the default basemap @mvl22 ? Many people don't get round to changing basemaps (including me)!

**Comment by mvl22** [comment]
It should be - may be a weird Mapbox GL caching/cookie issue.

If I open the site in an incognito window it's definitely selecting the correct basemap:

https://actdev.cyipt.bike/

**Comment by Robinlovelace** [comment]
Confirmed:

![image](https://user-images.githubusercontent.com/1825120/106935657-89456c80-6713-11eb-900e-b7ecd006c8df.png)

That makes me think of another issue: given that the popups (I think sensibly) show all the variables by default, should we include only the variables that are definitely of interest?

**Comment by Robinlovelace** [comment]
Looking at that data, I think we should only show route segment level data in route segments - i.e. route network data. These are three separate layers and I think there could be merit in allowing the user to see each one separately:

- Desire lines - idealised straight line routes that help think about new cycleway links in the network
- Routes - the actual routes people take from A to B - slightly back-pedalling on my previous statements I'm wondering if it's worth allowing people to see whole routes as they can in the PCT
- Route segments - that have all cycle traffic aggregated going through them, best visualised at the segment level

Thoughts @mvl22 and @joeytalbot ? Not opening an issue, one to discuss, in person tomorrow perhaps!

**Comment by mvl22** [comment]
> should we include only the variables that are definitely of interest

+1 - yes the real UI will mean scrutinising carefully what should and shouldn't be shown.
