### ISSUE TITLE
Final UI: website info page

### ISSUE THREAD

**Issue by Siequnu** [cyipt/actdev-ui#21]
Mockup concept for the ACTDEV website info page.

Should be a fairly simple page. Your thoughts?

<img width="988" alt="Screenshot 2021-02-23 at 22 02 52" src="https://user-images.githubusercontent.com/11821606/108854644-100aac80-7623-11eb-9810-c7a1eba7e914.png">

**Comment by Robinlovelace** [comment]
Looks good. If you can create a placeholder markdown file we can edit that. Great work, will make the project looked more polished.

**Comment by natesheehan** [comment]
Looks good! Two quick comments

- Stretch Goals needs spacing (or others should follow the same spacing)
- Text would look cleaner justified

**Comment by Robinlovelace** [comment]
Another + of having it in a prominent place in an easy-to-edit format like markdown: encourages others to contribute!

**Comment by mvl22** [comment]
Looks good.

**Comment by mvl22** [comment]
@Siequnu Perhaps you can just create a page in this repo at /about/index.md with the placeholder text so the others can add stuff there.

**Comment by Siequnu** [comment]
The about page is now published on the final-ui branch. It renders the markdown from here, so please add/remove at will.

https://github.com/cyipt/actdev-ui/blob/final-ui/about/about.md

**Comment by mvl22** [comment]
Now at https://actdev.cyipt.bike/about/

**Comment by Siequnu** [comment]
Closing as the page is now published.
