### ISSUE TITLE
Draft final text for the website info page

### ISSUE THREAD

**Issue by Siequnu** [cyipt/actdev-ui#22]
Is there anyone who can take action and draft the text to be put on the website info page (#21 )?

**Comment by Robinlovelace** [comment]
To avoid duplication of effort I suggest copy pasting relevant parts of this into a file called `info.md` or similar, link to it from this issue, and then we can all edit that: https://github.com/cyipt/acton/blob/master/vignettes/the-acton-project.Rmd

I think Patrick or Martin may be best placed to put the placeholder in the right place.

**Comment by Siequnu** [comment]
The MD file is located here.

https://github.com/cyipt/actdev-ui/blob/final-ui/about/about.md

**Comment by Siequnu** [comment]
Please do add/remove at will.

**Comment by Robinlovelace** [comment]
Changes made, looking good.

**Comment by Siequnu** [comment]
Thanks, the MD is pulling nicely and being generated into HTML. The info page isn't currently linked from the site-info page, expect that in the next few days.

**Comment by Siequnu** [comment]
Closing this as the page is now published and MD being collaborated on.
