### ISSUE TITLE
Programmatically generate site blurb

### ISSUE THREAD

**Issue by Siequnu** [cyipt/actdev-ui#25]
Currently I am generating a site blurb as per the mockup, as illustrated in  the screenshot below.
<img width="312" alt="Screenshot 2021-02-24 at 19 39 09" src="https://user-images.githubusercontent.com/11821606/108995402-08590f80-76d8-11eb-8df2-b2d223377c59.png">

It's generated by pulling in some of the site data and by [programmatically adding some lines at the end to indicate the site completion status](https://github.com/cyipt/actdev-ui/blob/81f7c1c1a96145374a0661061b450938080322f8/js/actdev.js#L707-L730)
```
var descriptionText = `This development in ${site.main_local_authority} will contain ${site.dwellings_when_complete} dwellings when complete.`
```

Posting this to get your opinions on how we can improve the blurb — adding or removing stats, etc. I personally quite like the idea of a short generated blurb, as it's a good way to surface lesser important stats without detracting attention from the headliners

**Comment by mvl22** [comment]
Change "The project" to "The development".

**Comment by Siequnu** [comment]
This has already been previously changed, to site.
<img width="760" alt="Screenshot 2021-02-26 at 14 04 01" src="https://user-images.githubusercontent.com/11821606/109261851-7e29bc00-783b-11eb-817f-984fa8b83b46.png">

**Comment by Siequnu** [comment]
No action for a week, and this seems to have settled: closing.
