### ISSUE TITLE
Photo gallery of each site

### ISSUE THREAD

**Issue by Siequnu** [cyipt/actdev-ui#27]
Our design envisages a small selection of site photos, however these haven't been added to all sites yet. These expandable thumbnails are a great way to get a quick contextual understanding of the site.

Any photo added to CycleStreets with the ACTDEV tag will appear. Once these have been added, we can automatically select and generate a carousel for each site.

<img width="803" alt="Screenshot 2021-02-24 at 20 01 33" src="https://user-images.githubusercontent.com/11821606/108997874-1d836d80-76db-11eb-9e9c-8aebbca3a9a7.png">

This is an UI issue, hence creating the issue here — although it's referenced in [actdev#97](https://github.com/cyipt/actdev/issues/97)

**Comment by Robinlovelace** [comment]
This looks very cool from a first glance.

**Comment by Siequnu** [comment]
Thanks — please note these are currently placeholders and clickable yet,, although the carousel is functioning.

**Comment by mvl22** [comment]
No need to define the list manually. Just pick these up dynamically from the CycleStreets API and parse out the JSON. Will need to parse out the site boundary extent and use that as the boundary passed to the API call.

**Comment by Siequnu** [comment]
> automatically select and generate

that's the plan!

**Comment by Siequnu** [comment]
The UI is now pulling automatically from the CycleStreets photomap based on a boundary geojson. Closing this UI issue, however, [actdev#97](https://github.com/cyipt/actdev/issues/97) remains pending (adding the actual photos)

**Comment by Robinlovelace** [comment]
Great work @Siequnu, it's looking great from the images above. I guess the latest version has not yet been deployed. Look forward to testing it!
