### ISSUE TITLE
Site cron job git pull not working

### ISSUE THREAD

**Issue by Siequnu** [cyipt/actdev-ui#28]
I just merged the final-ui branch with the master branch, however seems like the server automated git pull hasn't kicked in.

Should work fine on everyone's local install.

@mvl22 could you take a look at the cron job to make sure it's doing its doing?

**Comment by mvl22** [comment]
I'm not sure why this is happening, but actually this is sensible at the moment until the implementation of the main site-level UI is more advanced - otherwise we have no means to see the data being generated.

**Comment by Siequnu** [comment]
Thanks for the fix, @mvl22
