### ISSUE TITLE
Test embedding html versions of infographics

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/actdev-ui#29]
I've created a html version of the baseline mode split infographic for testing: https://rpubs.com/RobinLovelace/730913

See the commit below for the html and associated files in the actdev repo. There are probably better ways of doing this and svg may be a good option but this is just a starter to see what's possible.

I can output this in other formats based on plotly but there may be technical limitations with this approach. See https://plotly.com/ggplot2/ and this chapter of a free and open source book: https://plotly-r.com/improving-ggplotly.html for what is possible.

(Caveat: this is not my area so not sure I can make changes to this quickly, hence seeing this a question of testing only, may be quicker to do it 100% on the JS side in this repo but suspect that will take a lot of time looking at the code to generate these plots, we could output .csv/.json files in a file format that's easier to convert into these plots as another option).

**Comment by Robinlovelace** [comment]
It may be worth taking a look at and reproducing the code here to get a handle of what's going on: you can run it from the root directory of the `actdev` repo and it should work: https://github.com/cyipt/actdev/blob/main/code/mode-split-summary.R

**Comment by Siequnu** [comment]
This is a 4.66MB file which is unusable large. It appears to be loading some sort of massive blob at the start of the file. 

If this is the aforementioned way of embedding HTML from R, we'll have to seek another way unless we can reduce the size. (i.e. JS on my side based on your JSONs or CSVs, and using PNGs (with #434343/transparent background) for the more complex visuals).

**Comment by Siequnu** [comment]
I will experiment generating a JS mode-split chart and push that to the UI, should only be a couple dozen kb at max and will be quite flexible.

**Comment by Siequnu** [comment]
Current charts working well for now, closing this unless we decide to change the chart generation again.
