### ISSUE TITLE
Sites disappear when you click on them

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/actdev-ui#3]
Reproducible example shown below:

![Peek 2021-02-05 18-52](https://user-images.githubusercontent.com/1825120/107076404-4ce14180-67e3-11eb-8f84-7e4c6ad83adb.gif)

**Comment by Robinlovelace** [comment]
On another note, would it be possible to include a link to a planning application url associated with each site? Probably one for the data side, heads-up @joeytalbot.

**Comment by Robinlovelace** [comment]
Great fix and impressive auto-deploy. Follow-on issue as I document it: the popup is huge. Not sure what the best solution to this is, reduce the n. fields in the geojson probably being the simplest but not sure so posting here instead of opening a new issue for now.

![image](https://user-images.githubusercontent.com/1825120/107085807-e82ce380-67f0-11eb-98f9-e772937239ad.png)

**Comment by mvl22** [comment]
There was a partial fix 15 minutes before you posted that, at c33993e87438c82ed38d9558505b3cc3a74da9b2, but it probably came slightly later when the auto-deploy kicked in. Press shift-refresh if your browser still caches the CSS file.

I'm just about to commit the addition of the descriptions, btw.

**Comment by Robinlovelace** [comment]
![Peek 2021-02-05 20-46](https://user-images.githubusercontent.com/1825120/107087397-48248980-67f3-11eb-8d95-d6239d243f3e.gif)

Another issue, hovering over the site seems to permanently change the cursor - hope that's clear from the gif - opened just now in private window.

**Comment by mvl22** [comment]
> I'm just about to commit the addition of the descriptions, btw.

Descriptions now appear as tooltips, following upstream library support in https://github.com/cyclestreets/Mapboxgljs.LayerViewer/commit/2c07cf86442f1d5e776ceca616dde2a6f63cfc08.

Style could be improved a bit given the very long titles we have, but the mechanism is at least now in place.

![Screenshot 2021-02-05 at 20 54 03](https://user-images.githubusercontent.com/361423/107088144-6939aa00-67f4-11eb-93fc-546a595b435d.png)

**Comment by mvl22** [comment]
> hovering over the site seems to permanently change the cursor - hope that's clear from the gif

Yeah, I noticed that a few days ago. Hovering over a different layer object and moving away from that does reset it.

I think I know why this is happening. (The cursor leave function is not consistently implemented between standard layers and the special regions layer (activated by the `regionsFile` setting.)

**Comment by mvl22** [comment]
> hovering over the site seems to permanently change the cursor - hope that's clear from the gif

Fixed upstream in:
https://github.com/cyclestreets/Mapboxgljs.LayerViewer/commit/953553f45041a1b7436d5333d2d6bd0a3e29d0ae

(doh, terrible copy-and-paste bug!)
