### ISSUE TITLE
Change favicon

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/actdev-ui#30]
Currently it shows a bike but this project is about walking and cycling.

![image](https://user-images.githubusercontent.com/1825120/109217462-c8645c00-77ad-11eb-85c0-f8f5e65e5d0f.png)

I think there are some quick and easy options out there e.g. here: https://www.svgrepo.com/vectors/walking/

**Comment by Robinlovelace** [comment]
Something like this would be quick and easy and non-controversial. 

![image](https://user-images.githubusercontent.com/1825120/109218611-a61f0e00-77ae-11eb-8014-904e222f3baf.png)

Happy to hear of other ideas on this, may seem minor but definitely worth resolving IMO.

**Comment by Robinlovelace** [comment]
And at 152x152 pixels

![image](https://user-images.githubusercontent.com/1825120/109218970-fe561000-77ae-11eb-89d4-7a9bc37d67bd.png)

**Comment by Robinlovelace** [comment]
And 16 px which I think is how it would look in a browser, right? Clearly just an idea but keen to get this updated if possible.

![image](https://user-images.githubusercontent.com/1825120/109219136-247bb000-77af-11eb-8e21-3ffff184966e.png)

**Comment by Siequnu** [comment]
I'd suggest this, which will be more visually distinctive at 16x16.

<img width="60" alt="Screenshot 2021-02-26 at 11 32 42" src="https://user-images.githubusercontent.com/11821606/109251385-59771980-7826-11eb-9c3e-190e0000bbab.png">

**Comment by Siequnu** [comment]
Favicon, manifest, and other site metadata [added.](https://github.com/cyipt/actdev-ui/commit/28becd4a9ab57e6067195fa2a23c78f953e06e2b)
