### ISSUE TITLE
View Simulation button fails in Great Kneighton

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/actdev-ui#31]
Not sure if this is an issue A/B Street or ActDev side but when I clicked on the button I was sent to this address which failed: https://actdev.cyipt.bike/abstreet/?--actdev=undefined&--cam=14.4/52.17363/0.11218

Heads-up @dabreegster.

**Comment by Robinlovelace** [comment]
Looking at the URL I guess 'undefined' is the issue. I don't think the app should send people to that URL.

**Comment by dabreegster** [comment]
I saw that this morning.

> Looking at the URL I guess 'undefined' is the issue

Indeed, looks like a regression. Should be the site name `great-kneighton`.

**Comment by Robinlovelace** [comment]
Just looking at it from here: https://actdev.cyipt.bike/#15.39/53.744947/-1.360696

Which sent me here: https://actdev.cyipt.bike/abstreet/?--actdev=undefined&--cam=15.4/53.74495/-1.36070

**Comment by Siequnu** [comment]
This is a bug on my side with the href generation code.

**Comment by Siequnu** [comment]
[Fixed](https://github.com/cyipt/actdev-ui/commit/9711a0aa2b765b41bba04a9b67a52cd1203a8de2)
