### ISSUE TITLE
Handle missing in-site metrics and enable user to switch to any site

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/actdev-ui#32]
For sites that have yet to be built. Replacing https://github.com/cyipt/actdev/issues/110.

**Comment by Robinlovelace** [comment]
Illustration of a bug in functionality from the user perspective that I think is caused by this:

![Peek 2021-03-04 17-49](https://user-images.githubusercontent.com/1825120/110007952-1f6cb280-7d13-11eb-89a2-9506cd41a942.gif)

If you need placeholder data to solve the problem let me know but imagine it should be doable on the JS side. A fairly important one so will mark as MVP.

**Comment by mvl22** [comment]
The site now reports if the data is missing, saying that it cannot update the panel.

The nature of async loading of multiple pieces of data for a site means that the break in the chain with this first dataset breaks others loading, so the whole panel will not update. Whilst I could write a clever way of handling that situation, this seems overkill and not a good use of time given that the sites will be built shortly anyway.

**Comment by Robinlovelace** [comment]
This hasn't been fixed, as illustrated by the view from Bailrigg which used to work but is now unusable. This is a regression I think. Let me know if it is prohibitively hard to allow the app to work in the absence of in site metrics and I can 'fix' it on the data side by creating empty placeholder data as per https://github.com/cyipt/actdev/issues/122 but think it could make more sense to fix this in the front end code.

Illustration below.


![Peek 2021-03-07 08-34](https://user-images.githubusercontent.com/1825120/110234099-9cb94280-7f20-11eb-8e41-f5d1c71eeab5.gif)

**Comment by Siequnu** [comment]
> This hasn't been fixed, as illustrated by the view from Bailrigg which used to work but is now unusable. 

I don't think these developments ever worked, they just silently displayed the previous developments's data.

**Comment by Siequnu** [comment]
Just to clarify: are we not expecting then to have this data for these sites?

**Comment by Siequnu** [comment]
Fixed with [22c92e0](https://github.com/cyipt/actdev-ui/commit/22c92e0c9257cde70259a71aecdb344af863f22d)

**Comment by Robinlovelace** [comment]
> Just to clarify: are we not expecting then to have this data for these sites?

No because the data relies on roads. On many yet-to-be-started sites there are no roads.
