### ISSUE TITLE
Issues with the infographic/layer toggle

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/actdev-ui#33]
Currently the key ActDev layers can be toggled by the UI element shown below:

![image](https://user-images.githubusercontent.com/1825120/109288571-efa64200-781c-11eb-8d30-2cda06900a37.png)

Although the elements are larger, I'm not sure they are more prominent than the 'secondary layer' toggles:

![image](https://user-images.githubusercontent.com/1825120/109288722-28deb200-781d-11eb-983a-f41952d10034.png)

Issues with the current implementation:

- [x] Shows Cambridge regardless of the site selected - is the plan to use site-specific infographics instead? We could create nice infographics for each site or create more generic images that don't show a specific place
- [x] On small screens the ActDev layer toggles are hidden from the default view

One major shift could be to move those UI elements into the map, e.g. as a group of toggles above the 'secondary layer' toggles shown above so they are more prominent. A smaller solution could be to update the infographics to make them smaller, more generic and mention the fact that they update the map in the description, e.g. with the text:

> Site data: update map layers

**Comment by Robinlovelace** [comment]
See here for a design idea that could address both of the issues above, before/after below - would be more consistent way for users to interact with layers and show that ActDev and 'Secondary' elements are conceptually the same (they add/remove layers on the map): https://excalidraw.com/#room=3fa060ebdd7c20c6a24b,XSbcbt6ogB1OAGIsAvwCKg

![image](https://user-images.githubusercontent.com/1825120/109291149-888a8c80-7820-11eb-86f3-dc0a9692ba9d.png)

Edits welcome to that idea, useful to sketch while thinking though issues and potential solutions.

**Comment by mvl22** [comment]
> Shows Cambridge regardless of the site selected - is the plan to use site-specific infographics instead?

Per-site map implementation now in place, in 8debd8970f8da678c2db9c08ed3f990a36c327a6.

Rendering (e.g. colours) within these pending. (I basically have to translate the styles, currently turned into Mapbox GL styles, into Leaflet.js styles for these new mini maps.)

![Screenshot 2021-03-02 at 02 09 19](https://user-images.githubusercontent.com/361423/109585977-561cb000-7afc-11eb-99b7-3710794b7713.png)
![Screenshot 2021-03-02 at 02 09 09](https://user-images.githubusercontent.com/361423/109585983-574ddd00-7afc-11eb-8c52-55e4c982f793.png)

**Comment by Robinlovelace** [comment]
That looks like great progress. Impressive! A couple of major but I think easy-to-fix issues with the current implementation tested just now on a relatively small (1920x1080) screen with 150% size of text (default) on Windows:

1. The map toggles are not visible on the landing screen, you need to scroll down.

![image](https://user-images.githubusercontent.com/1825120/109617802-be848500-7b2e-11eb-9522-4e172c56e229.png)

2. After scrolling down it seems the UI elements do not fit on half screen infographic UI panel - is it possible to scale them?

![image](https://user-images.githubusercontent.com/1825120/109618121-158a5a00-7b2f-11eb-8dc8-8b274ba9ae41.png)

Tested on Microsoft Edge just now.

**Comment by Robinlovelace** [comment]
Good progress, 1 out of 2 sub-issues done :+1:

**Comment by mvl22** [comment]
It's on Patrick's list today to tighten up the metrics; we're going to reduce the main panel fonts a bit. Obviously we want to reduce up/down scrolling.

**Comment by Siequnu** [comment]
Some small screen adjustments have now been made and toggle are visible on mobile as well. We'll continue to optimise for small screens and mobile, but for now we've completed those first two checkboxes.
<img width="374" alt="Screenshot 2021-03-04 at 08 13 43" src="https://user-images.githubusercontent.com/11821606/109890079-98431e80-7cc1-11eb-8530-8bfc5b0d5254.png">
<img width="1042" alt="Screenshot 2021-03-04 at 08 13 52" src="https://user-images.githubusercontent.com/11821606/109890083-9a0ce200-7cc1-11eb-85b0-94fa9a2dc84f.png">
<img width="709" alt="Screenshot 2021-03-04 at 08 14 03" src="https://user-images.githubusercontent.com/11821606/109890088-9b3e0f00-7cc1-11eb-8680-6ac863bf907d.png">

**Comment by Robinlovelace** [comment]
Reopening because the second of the issues outlined above isn't fixed, unless I'm missing something, on my 2021 Windows laptop:

![image](https://user-images.githubusercontent.com/1825120/109938394-e0653f80-7cc7-11eb-834f-cf5777db58ae.png)

I don't think the toggles are available and I think it's not a css caching issue. Am I missing something?

Overall great progress on this, looking way better and more usable.

**Comment by mvl22** [comment]
There is work in hand to:

1) Rework the main metrics display (note the large space between the 47% and 35% lines - which gets even worse on smaller screens, when a third line appears)

2) Add a second breakpoint in the CSS for screen size to reduce down the font and other spacings when necessary. Currently it's just desktop vs mobile which we don't think is quite enough.

**Comment by Robinlovelace** [comment]
Small update from me: this is looking way better on a tiny screensize. Great work I think this one is almost done :tada: 

![image](https://user-images.githubusercontent.com/1825120/110216192-9b96ff80-7ea5-11eb-85f7-e3a670a5e9f0.png)

**Comment by Robinlovelace** [comment]
Interestingly the problem seems to get worse when expanding the screen gradually as shown in a test illustrated in the gif below.


![ezgif-4-0c4005373c6d](https://user-images.githubusercontent.com/1825120/110216359-a3a36f00-7ea6-11eb-94d3-f818df9cf830.gif)

**Comment by Siequnu** [comment]
@Robinlovelace could you clarify what are you illustrating with the this gif?

**Comment by Robinlovelace** [comment]
The fact that the bottom of the toggled layers, which allow the user to select route type, are hidden on some screens. This could be fixed by reducing the size of one or more elements in the current UI panel.

**Comment by Siequnu** [comment]
Got it — I've edited the break points so now the toggles should be more visible.

Not that in the original design we had a scrollable horizontal div here — only more recently have we switched to a grid layout that shows all toggles.

@Robinlovelace If that's it please check and verify issue status.

**Comment by Robinlovelace** [comment]
> @Robinlovelace If that's it please check and verify issue status.

Can you share a screenshot or GIF of the latest behaviour @Siequnu ?

**Comment by Siequnu** [comment]
<img width="1489" alt="Screenshot 2021-03-07 at 19 00 32" src="https://user-images.githubusercontent.com/11821606/110237517-77a3ee80-7f77-11eb-9373-444c2e55b085.png">
<img width="1318" alt="Screenshot 2021-03-07 at 19 00 35" src="https://user-images.githubusercontent.com/11821606/110237524-7e326600-7f77-11eb-8e80-936e0e552992.png">
<img width="1052" alt="Screenshot 2021-03-07 at 19 00 38" src="https://user-images.githubusercontent.com/11821606/110237525-7f639300-7f77-11eb-813e-69377c1e23f2.png">

**Comment by Robinlovelace** [comment]
Good enough for now, good work.
