### ISSUE TITLE
Add Key destinations and site buildings

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/actdev-ui#36]
Building on this issue opened by Patrick https://github.com/cyipt/actdev/issues/105 the next step on this is to allow users to visualise the data.

See an example of perhaps the largest key destinations file here: https://github.com/cyipt/actdev/blob/main/data-small/great-kneighton/trip_attractors.geojson

A more typical view of Key destinations is this for Handforth: https://github.com/cyipt/actdev/blob/main/data-small/handforth/trip_attractors.geojson

![image](https://user-images.githubusercontent.com/1825120/109521064-cd265a00-7aa4-11eb-976a-c7e9d4e9947c.png)

I'm not sure where best this should go but a new button next to the layers button on the map could work well. Marking as MVP as worth doing and builds a vision of what we can do in Phase II.

**Comment by Robinlovelace** [comment]
Note: I think the destinations could be tweaked and may be best represented as points. However, for the purposes of this prototype I suggest adding the buildings, not sure if I have time to add point versions as well.

**Comment by Robinlovelace** [comment]
Here's another dataset we saw during usability testing that should be a prominent and easy to access layer in the UI: https://github.com/cyipt/actdev/blob/main/data-small/aylesham/trip_attractors.geojson

**Comment by mvl22** [comment]
> trip_attractors.geojson

So that's basically 'POIs as buildings', basically, yes?

**Comment by Robinlovelace** [comment]
Correct

**Comment by mvl22** [comment]
Now in place.

**Comment by Robinlovelace** [comment]
Looking good to me!

**Comment by mvl22** [comment]
Legend will appear later, but that's part of other work to fix up legends from enum lists rather than range definitions.
