### ISSUE TITLE
Implement agreed colourscheme

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/actdev-ui#37]
The colourscheme for transport modes was agreed in https://github.com/cyipt/actdev/issues/112

Currently the app is showing this colourscheme:

![image](https://user-images.githubusercontent.com/1825120/109790858-b8afa200-7c09-11eb-8a3e-ba89332bcc1d.png)

Suggested quick fix: show the infographics such as 

![image](https://user-images.githubusercontent.com/1825120/109791109-ff9d9780-7c09-11eb-9340-73c684ee5f78.png)

https://github.com/cyipt/actdev/blob/main/data-small/lcid/mode-split-base.png

In the web app without changing the colours.

I'm happy to change the background of that, let me know @mvl22 / @Siequnu.

**Comment by mvl22** [comment]
The dynamic map, with the correct colours, went live overnight.

**Comment by Robinlovelace** [comment]
Looking good!

![image](https://user-images.githubusercontent.com/1825120/109794996-59a05c00-7c0e-11eb-8528-7113bd2c0ca5.png)

**Comment by mvl22** [comment]
Hope you like the animation when changing scenario, showing the active travel parts squeezing out the car mode :)
