### ISSUE TITLE
Landing page issues

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/actdev-ui#39]
A few usability issues jump out when looking at the new landing screen:

- [x] There is no way to search for ~~or even see~~ site names as far as I can tell
- [x] It could be useful to see where the sites are
- [x] I could be useful to be able sites by key metrics such as % active travel and number of dwellings

The first is the most important and I guess easiest to fix. Framing that as a question, is there a way for this to be fixed imminently?

**Comment by mvl22** [comment]
![Screenshot 2021-03-03 at 17 32 28](https://user-images.githubusercontent.com/361423/109846799-7193d200-7c46-11eb-9eee-4a248d06c24c.png)

**Comment by Robinlovelace** [comment]
Just so say great update on this, it's usable now 🎉 

![image](https://user-images.githubusercontent.com/1825120/109937855-430a0b80-7cc7-11eb-863d-0f82edfb9c89.png)

**Comment by Robinlovelace** [comment]
You probably already know this but clicking on a site doesn't take you to that site. If it's easy to fix that, and to give the sites their real names, that would be great (although I maintain that this landing page should take up a large % of developer time).

**Comment by mvl22** [comment]
> You probably already know this but clicking on a site doesn't take you to that site. If it's easy to fix that

That's now in place.

> and to give the sites their real names, that would be great

Pending.

> (although I maintain that this landing page should take up a large % of developer time).

I assume you meant should _not_.

Yes, it remains the case that the bulk of the development time has been at the site level, as initially directed.

**Comment by Robinlovelace** [comment]
Great work, this is looking great now. Many thanks Martin.

**Comment by Robinlovelace** [comment]
Update, I've tried Ashton Park and get some really unusable results:

![image](https://user-images.githubusercontent.com/1825120/110150422-2a891680-7dd7-11eb-9167-91352165da87.png)

Is that deliberate? It's only the 'in site metrics' that should be unavailable, not the whole left panel. Steps to reproduce and to check I'm not missing something obvious from a fresh Chromium instance that has not cache:

Go to https://actdev.cyipt.bike/

Click on the link on the Ashton park bar

Click OK when the error message pops up.

**Comment by mvl22** [comment]
> Is that deliberate? It's only the 'in site metrics' that should be unavailable, not the whole left panel.

https://github.com/cyipt/actdev-ui/issues/32#issuecomment-791468987

"The nature of async loading of multiple pieces of data for a site means that the break in the chain with this first dataset breaks others loading, so the whole panel for that site will not update. Whilst I could write a clever way of handling that situation, this seems overkill and not a good use of time given that the sites will be built shortly anyway."

If you want me to spend 3 hours reworking this, in advance of you supplying the data, I'm happy to do that.

Or is this what we have zero data for and will not have data for in future?

**Comment by Robinlovelace** [comment]
I can add some placeholder data for the in-site metrics to stop the whole thing tanking for sites that haven't yet been built. Preferable to the current behaviour would be to grey-out the unfinished sites.

**Comment by Robinlovelace** [comment]
See the 2nd column here for the yet-to-complete sites: https://github.com/cyipt/actdev/blob/main/data-small/all-sites.csv there's quite a few and I think an important feature of the tool is that it can provide info on planned sites, not just ones that have been built. It should take me ~30 minutes to add the placeholder data: https://github.com/cyipt/actdev/issues/122

**Comment by mvl22** [comment]
> for sites that haven't yet been built

Do you mean that your script hasn't built the site data, or that the developer hasn't built the site physically?

I thought that all sites should presumably have data as the 2011 position census position exists irrespective of the site. And presumably a Go Active scenario can be generated again irrespective of shovels on the ground.

Sorry, I am sensing there is confusion here as to what data we are expecting. If you don't and will not have particular datasets, we will definitely adjust the UI to cope with that.

**Comment by Robinlovelace** [comment]
> Do you mean that your script hasn't built the site data, or that the developer hasn't built the site physically?

Yes I think there is confusion. A few sites lack 'in site' files like this: https://github.com/cyipt/actdev/blob/main/data-small/allerton-bywater/in-site-cycle-rnet.geojson

E.g.: https://github.com/cyipt/actdev/blob/main/data-small/ashotn-park/in-site-cycle-rnet.geojson

However, as you'll see at https://github.com/cyipt/actdev/tree/main/data-small/ashton-park the other files are there.

So in answer to your question, I mean that some sites have not yet been built meaning that a few of the files (those that require on site roads) cannot be generated, hence the suggestion to generate a placeholder if you cannot find a work-around in the JS code.

Follow-up question after clarifying: can you find a work-around? Note that all the other files are there as you'll see here: https://github.com/cyipt/actdev/tree/main/data-small/ashton-park

I've been in discussion with @Siequnu about this for a couple of weeks - hope this is a good summary of the state of play and we have 2 strong options:

- [ ] Me create placeholder but basically empty files to prevent the JS code from crashing in the back-end code
- [ ] You work around this issue in the front end code

Don't mind which we go for, I suggest whichever is quickest.

**Comment by Siequnu** [comment]
Search function is now live
<img width="854" alt="Screenshot 2021-03-07 at 18 44 02" src="https://user-images.githubusercontent.com/11821606/110237151-2abf1880-7f75-11eb-8227-38b9e7519676.png">

That makes 3/3 out of the original issues — please add the above issue to these or create a new issue to track it.

**Comment by Robinlovelace** [comment]
:tada:

**Comment by Siequnu** [comment]
Fixed async loading issues in [22c92e0](https://github.com/cyipt/actdev-ui/commit/22c92e0c9257cde70259a71aecdb344af863f22d).
