### ISSUE TITLE
Rename Places to Destinations

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/actdev-ui#41]
Places is too vague. Destinations captures the purpose of the layer well: to show whether or not there is a wide range of ammenities nearby which happily there is for the residents of Great Kneighton:

![image](https://user-images.githubusercontent.com/1825120/109939487-04755080-7cc9-11eb-877b-315807c14c62.png)

**Comment by mvl22** [comment]
Yes, much better label; now in place.
