### ISSUE TITLE
"View simulation" button hard to notice

### ISSUE THREAD

**Issue by dabreegster** [cyipt/actdev-ui#43]
![Screenshot from 2021-03-05 20-46-24](https://user-images.githubusercontent.com/1664407/110195691-f53ef180-7df3-11eb-9728-e4d839e218af.png)
The button to launch A/B Street is quite de-emphasized. If that's a deliberate design decision, it's fine. But naturally I'd like to promote my work a bit more; what about adding [the logo](https://raw.githubusercontent.com/a-b-street/abstreet/master/data/system/assets/pregame/logo.svg) on the left side of that text as part of the button? In png form:
![logo_transparent](https://user-images.githubusercontent.com/1664407/110195713-25869000-7df4-11eb-96cf-0495d2338fa0.png)

**Comment by mvl22** [comment]
This was Robin's decision not to have this as the original button switcher within the map. His call on whether a logo should be added to the text that replaced that.

**Comment by Robinlovelace** [comment]
I think a more prominent button, e.g. below the scenario switcher, could work well. I don't think the simulation button should be a switch as it opens up new browser tabs. I think it's a good shout to add the logo if it doesn't make the UI area look cluttered.

**Comment by Robinlovelace** [comment]
Looking at the latest version, there is plenty of space for a 'view simulation' button in the first dive element. Just below the scenario toggle could work well I think:

![image](https://user-images.githubusercontent.com/1825120/110215622-b87e0380-7ea2-11eb-88d1-1d7e6046e863.png)

**Comment by Robinlovelace** [comment]
Here's a mock up of my thinking, could have an additional benefit of reducing empty space and reducing the height of that first element with benefits for #33.

Before and after:

![image](https://user-images.githubusercontent.com/1825120/110215967-59b98980-7ea4-11eb-8998-d30ca6e54452.png)



See editable version here - any suggested changes welcome: https://excalidraw.com/#room=5b2e8fea13e1ab5dc37c,p99Z9CPDMeDZw1HdLvwU4Q

**Comment by Robinlovelace** [comment]
Slightly updated mock-up. A few other potential improvements: most important, the scenario toggle didn't give any indication that it was changing the scenario ('Go active' lacked context) and I think for consistency the 'commuters' should be removed from the 'active commuters' bit, as commute is mentioned in the distance.

![image](https://user-images.githubusercontent.com/1825120/110216065-f5e39080-7ea4-11eb-9e28-463dd52d4c67.png)

**Comment by Siequnu** [comment]
I don’t think the buttons should be stacked or logically grouped as they have entirely different actions/results (i.e. toggling the numbers on the infographic side of the screen vs switching modally to an entirely new tab). 

My proposal would be to increase the AB link’s prominence in its current place, by adding the logo and possibly a radius border. 

If, after that, the positioning is still deemed unsatisfactory, I suggest we revisit the original concept which places this UI element on the map — as that’s logically the control with which the action is paired to. The original design imagined a toggle, which is logically not applicable at this stage, but we could have a button there instead.

**Comment by Robinlovelace** [comment]
> If, after that, the positioning is still deemed unsatisfactory, I suggest we revisit the original concept which places this UI element on the map — as that’s logically the control with which the action is paired to. The original design imagined a toggle, which is logically not applicable at this stage, but we could have a button there instead.

Happy to see that in action, would free up more space in left panel also and tackle the issue with the 'hidden toggles' that still I think reduces usability on some devices (not tried since yesterday). Could you provide a heads-up when you've got either a sketch or a version of the app with this implemented @Siequnu ?

**Comment by Siequnu** [comment]
<img width="667" alt="Screenshot 2021-03-07 at 17 52 36" src="https://user-images.githubusercontent.com/11821606/110235937-fbf17400-7f6d-11eb-828d-0446f3ef2fd0.png">
Here's how it is with a button and a logo. I think it makes sense conceptually to group it with the other external links at this stage.

**Comment by Robinlovelace** [comment]
Looks great to me :+1:

**Comment by Siequnu** [comment]
Closed with 1fa3f56d23545c3bcb69fc610c2ff99bb9cda5ba

**Comment by Robinlovelace** [comment]
You happy with this @dabreegster ?

**Comment by dabreegster** [comment]
This looks great; thank you! The outline makes it super clear that it's a button, and the grouping of external links makes perfect sense to me.
