### ISSUE TITLE
Route and route network line widths

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/actdev-ui#44]
Split out from #34, the lines are excessively thick. Also I'm not sure that #37 is fixed: it seems like a brick colour. And it still does not have a legend that describes what the user is seeing as described in #4. But the specific issue of max line widths should, I imagine, be a quick fix.

![image](https://user-images.githubusercontent.com/1825120/110233835-a772d800-7f1e-11eb-947c-e966b5c5777b.png)

**Comment by Siequnu** [comment]
These are now less thick.
<img width="862" alt="Screenshot 2021-03-07 at 21 31 10" src="https://user-images.githubusercontent.com/11821606/110241592-8a74ee00-7f8c-11eb-82a4-d2f44991f21d.png">
