### ISSUE TITLE
Default site level view should be further zoomed out

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/actdev-ui#45]
It is better than previous versions where the use zoomed straight into the site but still not zoomed out enough for the user to see context, e.g. that Great Kneighton is near Cambridge. I can see advantages of increasing the default zoom but think they are outweighed by the advantages of decreasing it. Example in which one's first instinct is to zoom out to see where it is and to see where all the routes are going:

![image](https://user-images.githubusercontent.com/1825120/110233893-0fc1b980-7f1f-11eb-9438-10fc52ba2587.png)

**Comment by Robinlovelace** [comment]
Given the default clockboard zoom is 11.9 I suggest setting the default site landing zoom to 12 so it's a bit like this (without the clockboard layer on by default):

https://actdev.cyipt.bike/great-kneighton/routenetwork/#11.88/52.17193/0.1211

**Comment by Siequnu** [comment]
This is now set to have the following default appearance:

<img width="879" alt="Screenshot 2021-03-07 at 19 27 38" src="https://user-images.githubusercontent.com/11821606/110238205-3c0b2380-7f7b-11eb-9155-4d8bb33d55e7.png">

@Robinlovelace can you confirm and close.

**Comment by Siequnu** [comment]
This is now set to pad to an equivalent of around 12 zoom around the developments.

**Comment by Siequnu** [comment]
Needs to be revisited regarding small screen fit.

**Comment by Siequnu** [comment]
<img width="860" alt="Screenshot 2021-03-07 at 22 13 23" src="https://user-images.githubusercontent.com/11821606/110242734-57355d80-7f92-11eb-8069-7f36f521b897.png">
Done.
