### ISSUE TITLE
Update ClockBoard infographic colour for NAs

### ISSUE THREAD

**Issue by Siequnu** [cyipt/actdev-ui#47]
<img width="800" alt="Screenshot 2021-03-07 at 22 28 43" src="https://user-images.githubusercontent.com/11821606/110243236-7af9a300-7f94-11eb-8ffe-e6203a3bd582.png">

**Comment by mvl22** [comment]
Fixed, via upstream library support for matching against null in https://github.com/cyclestreets/Mapboxgljs.LayerViewer/commit/a67c45816b74bfe4a18114b86c4dfb9e2fb316e0.

The segments remain clickable, i.e. the colour is transparent but the region is still present.

![Screenshot 2021-03-07 at 20 51 09](https://user-images.githubusercontent.com/361423/110254385-dcb31080-7f86-11eb-9586-0e630920d250.png)

**Comment by Robinlovelace** [comment]
Great work @mvl22. Note, after the new 'disag' code and data was pushed over the last 24 hours there should be fewer empty spaces. Really impressive. Next up on this: tell the user what the colours actually mean in the legend? That can be tracked in #4 .

**Comment by mvl22** [comment]
> tell the user what the colours actually mean in the legend?

That will be easier if the dictionary for that layer could be supplied. As you can see from the screenshot above, the raw variable names are showing through.

Needs a dartboard-dictionary.csv added at https://github.com/cyipt/actdev/tree/main/data-small.
