### ISSUE TITLE
Allow the user to see in site route network

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/actdev-ui#48]
Either as separate layers or as infographics.

These are the datasets I'm talking about that the user should be able to see as an infographic or on the map

- [x] https://github.com/cyipt/actdev/blob/main/data-small/great-kneighton/in-site-cycle-rnet.geojson
- [x] https://github.com/cyipt/actdev/blob/main/data-small/great-kneighton/in-site-drive-rnet.geojson
- [x] https://github.com/cyipt/actdev/blob/main/data-small/great-kneighton/in-site-walk-rnet.geojson

Split out from https://github.com/cyipt/actdev/issues/104

Would also be good to highlight in site metrics outlined in that issue - cannot immediately see how to do that from the latest version of the UI (which overall is looking lots better and is feeling way more usable):

![image](https://user-images.githubusercontent.com/1825120/110247702-7669c600-7f65-11eb-8955-5ddc9aafcd60.png)

Could that info be added to the 'Study area' (which could be renamed as 'Site info') UI widget?

**Comment by mvl22** [comment]
What story does that data tell?

**Comment by Robinlovelace** [comment]
> What story does that map route data tell and how is it useful?

It tell the story of how good the 'in site' design is. As discussed in the user testing session last week it's an important component of the overall suitability of a site from a walking and cycling perspective (although not as important as the routes outside the site). 

See further discussion of what it can tell us here: https://github.com/cyipt/actdev/issues/93

**Comment by mvl22** [comment]
What should the colour breakpoints be?

**Comment by Robinlovelace** [comment]
> What should the colour breakpoints be?

I think using the mode colours for each route network and a relative thickness set to a sensible maximum would be ideal, if that makes sense. Can provide more detailed ideas and discuss if needs be.

**Comment by Robinlovelace** [comment]
This is done :tada: Leaving open - can close when 'in-site-circuity' metrics are on the landing page. Note: these metrics were previously in there but caused issues on some sites that lacked metrics like handforth. Discussed with @mvl22.

**Comment by mvl22** [comment]
> This is done 🎉 Leaving open - can close when 'in-site-circuity' metrics are on the landing page.

That is covered in existing issue:
https://github.com/cyipt/actdev-ui/issues/19#issuecomment-794344889
