### ISSUE TITLE
Spurious visualisations shown to user

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/actdev-ui#49]
See example provided by @Siequnu in https://github.com/cyipt/actdev/issues/129. I'm not sure if this is a data issue or a UI issue. I suspect the underlying issue was caused by a slight change in the position (but not names) of data fields in the .geojson files. Opening this issue here in case it is a UI issue as a companion. It may be possible to solve the problem either in this repo or the actdev repo and happy to fix any data issues that arise.

**Comment by Siequnu** [comment]
This is a mode-split data issue.
