### ISSUE TITLE
Adding a new basemap hides data

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/actdev-ui#50]
It shouldn't - according to @joeytalbot it was discussed already and may be a MapBox problem that is difficult to solve. Any ideas on what would be required to fix this? Could be marked as 'wont fix' if prohibitive but would be nice to be able to change the basemap without removing overlay data from the user's view.

Example below from https://actdev.cyipt.bike/aylesham/routenetwork/#10.89/51.265/1.1904

![Peek 2021-03-08 10-10](https://user-images.githubusercontent.com/1825120/110307471-d5c3e680-7ff6-11eb-9665-7fa1bd505c8a.gif)

**Comment by mvl22** [comment]
This is a horrendous Mapbox GL JS bug that is still open.

@Siequnu We solved this using the 'nuclear option' before - can you find what we did to fix that, by doing a window.reload? I can't see where that is.

In checking this one out, I've had to fix a series of bugs that have surfaced in the handling of layers and their URLs. The window.reload nuclear option relies on the state being in the URL properly, which broke with the region switcher feature. That's now fixed upstream:
https://github.com/cyclestreets/Mapboxgljs.LayerViewer/commits/master
though there's one remaining issue I need to checkout. But basically, doing a page refresh now should much more correctly retain the layer state, buttons, etc, as the layers are in the URL.

**Comment by mvl22** [comment]
Now in place.

This was dependent on a pile of other fixes for maintaining the layer state (as initially read from the URL) properly.
