### ISSUE TITLE
Add A/B Street Logo to the landing page

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/actdev-ui#52]
I see 

![image](https://user-images.githubusercontent.com/1825120/110354558-36234a00-8030-11eb-9541-503c0b2c3d45.png)

Can we add the A/B Street logo in there? Heads-up @dabreegster

**Comment by mvl22** [comment]
And PlanIt then?

**Comment by Robinlovelace** [comment]
> And PlanIt presumably then, if the intention is to include the list of those involved rather than the list of formal project partners?

:+1: although I recall Andrew said not to include a link to his project in the workshop blurb when asked. I would say add a link at the very least, good to have lots of links to project partners.

**Comment by dabreegster** [comment]
An abst logo would be great! Linking to `abstreet.org` is fine. https://github.com/dabreegster/abstreet/raw/master/data/system/assets/pregame/logo.svg is an SVG, and here's the png:
![logo_transparent](https://user-images.githubusercontent.com/1664407/110381907-00219e00-800f-11eb-9d71-a3660dd39824.png)

**Comment by mvl22** [comment]
Now added; sizing on smaller screens will be dealt with when mobile support on front page in place.

**Comment by Robinlovelace** [comment]
Looking good! It's easy to get bogged down with issues and perhaps the 'issue tracker' way of working is too conducive to finding fault rather than finding opportunities and strengths. So it bears repeating: this is looking amazing!

![image](https://user-images.githubusercontent.com/1825120/110389976-3128bf80-805d-11eb-83fc-c8591d1aeb30.png)

Impressive rate of progression, very happy with the feel. More work to do to smooth out a number of rough edges but the concept is there and for a prototype it's outstanding compared with other similar projects I've been involved with.
