### ISSUE TITLE
Mode split transport graph lacks units

### ISSUE THREAD

**Issue by dabreegster** [cyipt/actdev-ui#56]
![Screenshot from 2021-03-09 07-44-04](https://user-images.githubusercontent.com/1664407/110497483-55ab8880-80ab-11eb-963f-3288a65a4e79.png)
X axis is count, Y axis is km, but that's not clear at all from the tooltip or image

**Comment by Robinlovelace** [comment]
Can you share a screenshot of the fixed graphs for completeness? Good practice.
