### ISSUE TITLE
Task: Deploy site on a second server as fallback

### ISSUE THREAD

**Issue by mvl22** [cyipt/actdev-ui#57]
In the unlikely event that the server that the site is on becomes unavailability due to a datacentre error, we should have a second hot copy set up.

I will deploy the site on another server.

**Comment by dabreegster** [comment]
Relatedly: is it worth copying all of the static assets hosted by Github onto this server? I poked around Google and https://docs.github.com/en/github/site-policy/github-terms-of-service, but couldn't find a SLA for raw.githubusercontent.com.

**Comment by mvl22** [comment]
OK, the site is now deployed at a second location, and will remain until just after the workshop.

I will report the URL privately.
