### ISSUE TITLE
Update route network legend title

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/actdev-ui#59]
Minor follow-up to #4 (great work on that btw).

Currently it is not 100% clear that the colours relate to route busyness as there is no mention of colour:

![image](https://user-images.githubusercontent.com/1825120/110643695-495b2480-81ac-11eb-9283-5cc4577712a2.png)

Source: https://actdev.cyipt.bike/allerton-bywater/routenetwork,destinations/#12.89/53.75204/-1.36396

Some people may figure this out but it's good to be explicit.

Suggested fix: Update the legend so it says:

Old:

```
Route network

Routes from the site, segmented by section, showing the busyness rating. (Thicker lines indicate more people.)
```

Suggested, which is shorter and I think clearer:

```
Route network

Segments on cycling/walking routes. Thickness represents flow. Colour represents busyness. 
```

Same applies to the Route legend: https://actdev.cyipt.bike/allerton-bywater/routes,destinations/#12.89/53.75204/-1.36396

**Comment by mvl22** [comment]
Thanks, that text is much better.

![Screenshot 2021-03-10 at 19 28 14](https://user-images.githubusercontent.com/361423/110686023-d2875100-81d6-11eb-9d00-50de15ee6397.png)
