### ISSUE TITLE
Change 'Cyclability ratings' UI option to 'Walkability and Cyclability'

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/actdev-ui#6]
![image](https://user-images.githubusercontent.com/1825120/107403217-c0919000-6afc-11eb-93d7-197e2df5adbf.png)

**Comment by mvl22** [comment]
I will do this and implement a setting to switch between cycleability / walkability, with the latter giving a message that we don't have ratings available for that yet.

**Comment by Robinlovelace** [comment]
Good plan. Thanks!

**Comment by mvl22** [comment]
Instead I did this as a combined panel, to be rather more user-friendly than using a placebo control as I first envisaged.

**Comment by Robinlovelace** [comment]
Very nice!
