### ISSUE TITLE
Simulation link is down

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/actdev-ui#60]
It currently takes me here: https://actdev.cyipt.bike/abstreet/?--actdev=great-kneighton&--cam=12.3/52.19582/0.12904

**Comment by Robinlovelace** [comment]
Also fails for the base url: https://actdev.cyipt.bike/abstreet/?--actdev=great-kneighton

Heads-up @mvl22 and @dabreegster.

**Comment by dabreegster** [comment]
I pushed https://github.com/cyipt/actdev/releases/download/0.1.17/abst_actdev.zip last night. Just confirmed it has lots of files missing from that directory listing -- notably `index.html` and `game.js`. Did the unzip fail? https://github.com/cyipt/actdev-ui/commit/a01ddc92f02a570ff4d1490b1edf3c59abc5f81f doesn't look like it would break anything, but timeline-wise, it could be related.
