### ISSUE TITLE
The JTS popup is overwhelming

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/actdev-ui#65]
![Peek 2021-03-10 21-47](https://user-images.githubusercontent.com/1825120/110702473-762e2c80-81ea-11eb-860e-758fe6500b1f.gif)

The JTS data is looking useful and good for Great Kneighton. However:

- [ ] The legend title does not say which field in the popup the colours represent
- [ ] The popup is too big

Suggested fields to show (for walking+pt/cycling/driving):

- Nearest food store (important because it's not in the existing data, unlike distance to town/employment)
- Nearest primary school

I cannot recall which field the colourscheme reports but that should be easy to add to the legend.

Is there a way to allow the user to 'See more info' to see fields that will be hidden in the default pop-up when this issue is fixed?

**Comment by Robinlovelace** [comment]
<details>

![image](https://user-images.githubusercontent.com/1825120/110705356-32d5bd00-81ee-11eb-9f6b-ca0a9eee1ae9.png)

**Comment by mvl22** [comment]
Fixed.

Popups will auto-scroll beyond a certain height.

Legend states the field used.

![Screenshot 2021-03-10 at 23 17 15](https://user-images.githubusercontent.com/361423/110711070-d1feb280-81f6-11eb-8181-0b7f0dfb16d0.png)

![Screenshot 2021-03-10 at 23 18 06](https://user-images.githubusercontent.com/361423/110711158-f5c1f880-81f6-11eb-88cd-b9e2fd658d2d.png)

**Comment by Robinlovelace** [comment]
From the site but to where?

**Comment by mvl22** [comment]
“to centres of employment” it says. Am I misunderstanding something?

**Comment by Robinlovelace** [comment]
> “to centres of employment” it says. Am I misunderstanding something?

No sorted now - I was referring to when it was like this.

![image](https://user-images.githubusercontent.com/1825120/110769157-cd1a1d00-824f-11eb-9ec2-08321ca20952.png)

Sorted now!

**Comment by mvl22** [comment]
Make sure to force refresh when testing any development website.
