### ISSUE TITLE
Manual not accessible on mobile

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/actdev-ui#67]
Just tried to read it on mobile. Can the mostly empty right column be removed? Will allow people to read about the tool on more devices.

Note to self we should say that the tool was not designed to be used from smartphones which is fine.

From a mobile, can add details later.

**Comment by mvl22** [comment]
Patrick is currently working on some mobile layout changes.

**Comment by Robinlovelace** [comment]
Great. To save time I suggest that only the landing page, report and manual need to be updated - just a question of moving the right hand bar which seems to be a fixed size I think.

Removing the mostly empty right hand column for the Manual and Report will benefit people using laptops also.

**Comment by mvl22** [comment]
Yes, Patrick is doing standard responsive design stuff.

There is already basic mobile support on the main site-level page but it hasn't been tuned.

**Comment by Siequnu** [comment]
This has now been fixed!
<img width="239" alt="Screenshot 2021-03-11 at 22 24 31" src="https://user-images.githubusercontent.com/11821606/110801813-8e6c7d00-82b8-11eb-9cd1-874e4d0752cd.png">
