### ISSUE TITLE
Update background colour

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/actdev-ui#7]
As discussed with @mvl22 the current bright red is not ideal - I think even a stopgap e.g. from one of the themes here https://github.com/cyipt/actdev/issues/48 would be fine at this Phase I prototype stage.

**Comment by mvl22** [comment]
Gone blue in beda5ac1d61f05615c5aa5ebf26b016db5f205cc.

**Comment by Robinlovelace** [comment]
Great to see the new colours, shown in all their 'cool glory' in the screenshot below (which also highlights a few remaining issues in the 'Travel data' (as it could accurately be called to contain rnets, routes and desire lines) section:

![image](https://user-images.githubusercontent.com/1825120/107434195-57247800-6b22-11eb-92d2-c909ab321765.png)

**Comment by mvl22** [comment]
Those other layers added in 021f89c92ddb6505ce2f96035a863c9b9e71fb79.
