### ISSUE TITLE
Clicking on a site on the map doesn't take you to the site data

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/actdev-ui#70]
As illustrated below. It's great to be able to get to the site by searching its name. But it would be even better if you could navigate through different sites using geographic location on the map.

![Peek 2021-03-11 14-38](https://user-images.githubusercontent.com/1825120/110804170-d1f2c700-8277-11eb-99ac-d96886b39bd1.gif)

**Comment by Robinlovelace** [comment]
Related issue: there is a wealth of info at the site level but the pop-up is only showing the site name, as documented in #64.

**Comment by mvl22** [comment]
I thought this would be hard, but actually I found an elegant solution which implements it, in https://github.com/cyclestreets/Mapboxgljs.LayerViewer/commit/d2b4948f1db725004e9dc53ee1e565b3eea69412.

**Comment by Robinlovelace** [comment]
:tada: important feature.
