### ISSUE TITLE
New site

### ISSUE THREAD

**Issue by natesheehan** [cyipt/actdev-ui#74]
I have added a new site as part of https://github.com/cyipt/actdev/issues/156

The site is now showing on the act-dev website (https://actdev.cyipt.bike/exeter-red-cow-village/buildings/#12/50.73196/-3.54136), however, there are some funky kinks. 

- sidebar text does not reflect the new site details
- new site is not added to the home page

I'm assuming this might be a problem from my side, but let me know.

**Comment by Robinlovelace** [comment]
Thoughts @mvl22 ? I guess there are a few stages on the ui side that are needed for the automated inclusion of new sites.

**Comment by natesheehan** [comment]
https://actdev.cyipt.bike/northwick-park/buildings/#12/51.57456/-0.31365 (another new site, for brent, london)

**Comment by mvl22** [comment]
Presumably this which we highlighted was important for you to fix, but remains unaddressed.

https://github.com/cyipt/actdev/issues/153

**Comment by Robinlovelace** [comment]
Heads-up @mvl22 it seems the latest batch of CSVs have broken the site: 
![image](https://user-images.githubusercontent.com/1825120/114740552-dbbd8d80-9d41-11eb-8ee7-8eb584bb9f89.png)

PR: https://github.com/cyipt/actdev/pull/160/files

Looks fine to me. Are the number of sites or other variable hardcoded in the JS?

![image](https://user-images.githubusercontent.com/1825120/114740714-027bc400-9d42-11eb-993f-3e5b13847898.png)

**Comment by mvl22** [comment]
No, it's because you haven't updated this file to add the name, etc.:

https://github.com/cyipt/actdev/blob/main/data-small/all-sites.csv

**Comment by Robinlovelace** [comment]
Makes sense, thanks @mvl22 . Final steps in the build process when adding new sites should definitely take care of that. Heads-up @natesheehan .

**Comment by natesheehan** [comment]
ok https://github.com/cyipt/actdev/blob/main/data-small/all-sites.csv now contains the updated sites. 

Again, this is placed in the `site-mertics.r ` file.

**Comment by natesheehan** [comment]
<img width="866" alt="Screenshot 2021-04-14 204041" src="https://user-images.githubusercontent.com/22789869/114769230-d96b2b80-9d61-11eb-9f0f-47edf51f6c58.png">

map view looking good for new sites now.

I am still getting a blank home page with the same error message (have cleared my cache)

**Comment by Robinlovelace** [comment]
> I am still getting a blank home page with the same error message (have cleared my cache)

I think there may be still a site missing from https://github.com/cyipt/actdev/blob/main/data-small/all-sites.csv

I added Chapeltown Cohousing.

**Comment by Robinlovelace** [comment]
Potential cause:

![image](https://user-images.githubusercontent.com/1825120/114771058-0ddfe700-9d64-11eb-90bb-e468a5a141bf.png)

**Comment by Robinlovelace** [comment]
Reprex:

```
> all_sites_csv = read.csv("data-small/all-sites.csv")
> all_sites_geojson = sf::read_sf("data-small/all-sites.csv")
> setdiff(all_sites_csv$site_name, all_sites_geojson$site_name)
character(0)
> setdiff(all_sites_geojson$site_name, all_sites_csv$site_name)
character(0)
> summary(all_sites_geojson$site_name %in% all_sites_csv$site_name)
   Mode    TRUE 
logical      37 
> all_sites_mode = read.csv("data-small/mode-share-sites-baseline.csv")
> setdiff(all_sites_csv$site_name, all_sites_mode$site_name)
character(0)
> setdiff(letters[1:3], letters[1:4])
character(0)
> setdiff(letters[1:4], letters[1:3])
[1] "d"
> diffobj::diffObj(all_sites_mode$site_name, all_sites_csv$site_name)
```

**Comment by Robinlovelace** [comment]
We can purge 'chapletown' rows - typo.

**Comment by natesheehan** [comment]
Yep sounds good. 

Apart from a folder with jts-lsoas, I can't currently see anything for Chapeltown cohousing on my main branch (have you pushed anything recently? or are you on a seperate branch?).

**Comment by Robinlovelace** [comment]
> Apart from a folder with jts-lsoas, I can't currently see anything for Chapeltown cohousing on my main branch (have you pushed anything recently? or are you on a separate branch?).

Aha didn't push. I will hold my horses until we fix this to reduce the number of moving parts.

**Comment by Robinlovelace** [comment]
> Apart from a folder with jts-lsoas, I can't currently see anything for Chapeltown cohousing on my main branch (have you pushed anything recently? or are you on a separate branch?).

But misspelt chapletown is still in there: https://github.com/cyipt/actdev/search?q=chapletown

**Comment by natesheehan** [comment]
aha, so it is! Yes definitely purge that

> > Apart from a folder with jts-lsoas, I can't currently see anything for Chapeltown cohousing on my main branch (have you pushed anything recently? or are you on a separate branch?).
> 
> Aha didn't push. I will hold my horses until we fix this to reduce the number of moving parts.

**Comment by natesheehan** [comment]
Homepage looking good for me now! 🚀 good spot @Robinlovelace !

**Comment by Robinlovelace** [comment]
Reproducible example, complete with 'xeter' location ; ) https://actdev.cyipt.bike/

![image](https://user-images.githubusercontent.com/1825120/114779085-8eefac00-9d6d-11eb-946e-56c6f846b947.png)

Can we close this now? I think so. The build process needs a few more tests but it sounds like you have some sites to add to double check the build system is solid @natesheehan over in the actdev repo.

**Comment by natesheehan** [comment]
Wait think it needs one _final commit_  the same needs to be done in order for the go active to work. I will do now

**Comment by natesheehan** [comment]
Ok, the home page now fixed! Yes, i think some tests and I think i know the reason why for the duplication. I'll create a separate actdev ticket for it and close this one!

**Comment by mvl22** [comment]
Well done resolving that inconsistency. Hopefully you now have a clear list of what files make a complete addition.

Do add more as you wish, the site should just react to whatever’s there.
