### ISSUE TITLE
New abstreet deployment not unzipped properly

### ISSUE THREAD

**Issue by dabreegster** [cyipt/actdev-ui#75]
I pushed https://github.com/cyipt/actdev/releases/tag/0.1.20, which slightly modifies the directory structure. I was assuming the entire .zip is unpacked into https://actdev.cyipt.bike/abstreet/, but it looks like this isn't the case -- https://actdev.cyipt.bike/abstreet/?--actdev=exeter-red-cow-village&--cam=12.0/50.73196/-3.54136&--actdev_scenario=base shows a directory listing only with `system`. Looking at the .zip, it's missing `abstreet.css`, `index.html`, and an `abstreet/` directory.

**Comment by dabreegster** [comment]
I deleted the release to restore the live deployment. I've seen the shell script in another repo that does the deployment, looking for it now...

**Comment by dabreegster** [comment]
Hmm, https://github.com/cyipt/actdev-ui/blob/master/.update-abstreet.sh should be fine. It unzips and renames `abst_actdev` to `abstreet`. The inner `abstreet/abstreet` dir should be fine.

**Comment by dabreegster** [comment]
The old version is restored. There's some URL rewriting going on that I think is messing things up -- https://actdev.cyipt.bike/abstreet/abstreet shouldn't work in the old deployment, but it redirects

**Comment by dabreegster** [comment]
https://github.com/cyipt/actdev-ui/blob/a7141702bfdbab6edb928946bb709d229f0efe3e/.htaccess#L3
I think this is the culprit.

Martin, this is the new directory structure:

```
> find abst_actdev/ | grep -v system
abst_actdev/
abst_actdev/abstreet
abst_actdev/abstreet/wasm_pkg
abst_actdev/abstreet/wasm_pkg/game_bg.wasm.d.ts
abst_actdev/abstreet/wasm_pkg/game_bg.wasm
abst_actdev/abstreet/wasm_pkg/package.json
abst_actdev/abstreet/wasm_pkg/game.js
abst_actdev/abstreet/wasm_pkg/.gitignore
abst_actdev/abstreet/wasm_pkg/game.d.ts
abst_actdev/abstreet/abstreet.bundle.js
abst_actdev/abstreet.css
abst_actdev/index.html
# abst_actdev/system still exists, with many nested directories and bin.gz files
```

Do you understand what the issue is? Thanks. I can modify the directory structure in here however's needed.

**Comment by mvl22** [comment]
I've just tried a site and it's loaded fine, so tbh I'm not sure what the above discussion is asking me to do.

**Comment by dabreegster** [comment]
It's working now because I deleted the new release, so that the simulation wouldn't be broken overnight.

https://github.com/cyipt/actdev/releases/download/0.1.19/new_abst_actdev.zip is the new file. When I opened any sim link with this version deployed, I got a directory listing that was missing the `abstreet` subdirectory and `index.html`.

**Comment by mvl22** [comment]
Can you try adding a new version and see if the deploy does it OK this time?

I realise this was the second time this failed, but I can't see anything obviously wrong. If the server was very busy with low RAM at the time, potentially that might be a cause.

**Comment by dabreegster** [comment]
Check https://actdev.cyipt.bike/abstreet/?--actdev=exeter-red-cow-village&--cam=12.0/50.73196/-3.54136&--actdev_scenario=base
https://github.com/cyipt/actdev/releases/tag/0.1.21 is deployed

**Comment by dabreegster** [comment]
> If the server was very busy with low RAM at the time, potentially that might be a cause.

Should https://github.com/cyipt/actdev-ui/blob/a7141702bfdbab6edb928946bb709d229f0efe3e/.update-abstreet.sh#L31 have a `set -e` to abort the script if any command fails? If `unzip` only happens partially, we should keep the previous version.

The .zip _is_ growing -- up to 730MB. Part of that is inevitable as we hit 40+ sites. Part of it could be improved with significant abst effort to represent the map model more compactly.

**Comment by mvl22** [comment]
I've added `set -e` - most of our other scripts use that already so I'm surprised I'd forgotten to use this here.

I think the issue was lack of disk space. We have 2GB free (having now deleted some things) - that needs to include both the zip file and its unzipped version.

As an obvious and general comment, an architecture that involves an ever-growing massive single zip file is bound not to scale and probably needs to be rethought.

**Comment by dabreegster** [comment]
> an architecture that involves an ever-growing massive single zip file is bound not to scale and probably needs to be rethought.

Agreed, that's why I wanted to establish an upper bound on the number of new sites in the next few months. As an improvement over the .zip, I could start shipping you a much smaller .zip with just the application and a Linux executable to fetch all of the site data. That updater tool would be resumable and idempotent; if it failed for any reason in the middle, you could just re-run it.

> I think the issue was lack of disk space. Should all be there now.

Thanks! It looks like the files are in-place now. I've spotted a bug with the deployment; the game is trying to load URLs like https://actdev.cyipt.bike/abstreet/data/system/gb/poundbury/maps/center.bin.gz, but there shouldn't be any `data/` there. It's a problem on my end. I can fix it later this week and push a new release. In the meantime, shall I delete the new release so we revert back to the old working one?

**Comment by mvl22** [comment]
Just push another release that is the same as the earlier version, and it should upgrade (well, downgrade) to that.

**Comment by dabreegster** [comment]
https://actdev.cyipt.bike/abstreet/?--actdev=exeter-red-cow-village&--cam=12.0/50.73196/-3.54136&--actdev_scenario=base
All working now, thanks!
