### ISSUE TITLE
Manual down

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/actdev-ui#77]
It's currently blank: https://actdev.cyipt.bike/manual/

![image](https://user-images.githubusercontent.com/1825120/142203760-57f20301-f68e-4633-999d-eaa413efe534.png)

Any ideas of the cause and hopefully quick fix @mvl22 ?

**Comment by mvl22** [comment]
Fixed.

**Comment by Robinlovelace** [comment]
:tada: thanks
