### ISSUE TITLE
Routes not showing

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/actdev-ui#79]
As discovered by @joeytalbot and in preparation for a presentation last week. Any ideas what's causing this @mvl22 ?

**Comment by mvl22** [comment]
Fixed, sorry about that. Regression in one of the libraries.

**Comment by Robinlovelace** [comment]
Great work Martin, thanks for the quick fix! Looking good.

![image](https://user-images.githubusercontent.com/1825120/154814346-d1f36e0e-f880-4203-bde4-27cf979116f4.png)

**Comment by Robinlovelace** [comment]
Out of interest what was the fix? Cannot see it in commit history.
