### ISSUE TITLE
Implement agreed colourscheme for route segment busyness

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/actdev-ui#8]
There are a few issues here but it's worth putting them together I think.

The `rnet*.geojson` files are route network layers. We decided that the UI will allow visualisation of route data in 3 ways, in this order:

- [x] Route network data (perhaps on by default) - this is currently shown when "Desire line routes" is selected
- [x] Route data - the whole route geometries
- [x] Desire lines - straight desire lines

How should these be split out from the current UI element?

![image](https://user-images.githubusercontent.com/1825120/107406500-6692c980-6b00-11eb-9fb1-913883883a59.png)

I'm not sure but they are conceptually the same thing which is 'Travel/route data' although it may make more sense to split them up rather than grouping them in a single UI element. Please take the initiative @mvl22 and @Siequnu and split-out those three elements in a way that works as a starter for 10. 

The other issue is simpler: the colour scheme agreed in https://github.com/cyipt/actdev/issues/48 has not yet been implemented. Please point me to the bit of code defining the colourscheme to help me get my head round it.

**Comment by mvl22** [comment]
> How should these be split out from the current UI element?

I was going to implement a control that switches between the three of them, so the user can choose, as they seemed conceptually similar to me - journeys between A & B, which happen to show the busyness where that exists.

**Comment by mvl22** [comment]
> Please point me to the bit of code defining the colourscheme to help me get my head round it.

https://github.com/cyipt/actdev-ui/blob/master/js/actdev.js#L90-L96

Refs: https://github.com/cyipt/actdev/issues/48#issuecomment-771504588

There was obviously no point trying to put in place a working colour ramp for these lines until the scale was known, but now we are (I think) getting this formally defined then that work can now be started.

**Comment by Robinlovelace** [comment]
1 - 10 for the lines. Good point, we've come a long way today alone and we're pretty close to an MVP. Great work.

**Comment by mvl22** [comment]
> We decided that the UI will allow visualisation of route data in 3 ways, in this order

Now each shown, currently as distinct layers.

Options to change between variations (e.g. quiet/fast) to follow.

**Comment by Robinlovelace** [comment]
Great work @mvl22, thanks for the update - I need to get on the ClockBoard data generation.

**Comment by Siequnu** [comment]
Closing as implemented.

**Comment by Robinlovelace** [comment]
Thanks but can you share a screengrab to show what you mean  @Siequnu  ? I still see issues with the route and route network layer, not least that the line widths are on average too think. The colours do not match what they say. Busyness should be the colour and width should be the width and this looks like it hasn't yet been implemented.

![image](https://user-images.githubusercontent.com/1825120/109940355-dd6b4e80-7cc9-11eb-853b-3a3ac007d3a6.png)

**Comment by Robinlovelace** [comment]
Reopening because I'm still seeing the brick colours, not the colourscheme we agreed.

**Comment by Siequnu** [comment]
This colour-scheme is now in effect. Brings out some really interesting data too.
<img width="865" alt="Screenshot 2021-03-07 at 22 03 46" src="https://user-images.githubusercontent.com/11821606/110242431-10933380-7f91-11eb-9b8b-c88f924ab036.png">

**Comment by Robinlovelace** [comment]
Important fix :+1: Perhaps equally important is the legend: where does it say that this is busyness? See #4.
